[package]
name = "dagsverk-ui"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
dagsverk-core.workspace = true
gpui.workspace = true
unicode-segmentation.workspace = true

[lib]
path = "src/lib.rs"

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
